/**
 * locais-data.js — Dados dos locais/estabelecimentos turísticos de São Mateus do Sul
 * Cada local com página dedicada em /local?id=<slug>
 */

const locaisData = {

    'igreja-matriz': {
        id: 'igreja-matriz',
        nome: 'Igreja Matriz São Mateus',
        subtitulo: 'Patrimônio Histórico · Turismo de Fé',
        badge: '⛪ Patrimônio',
        descricao: 'A Igreja Matriz de São Mateus do Sul é o principal símbolo arquitetônico da cidade. Construída no estilo neogótico pelos imigrantes poloneses no início do século XX, domina o centro da cidade com sua torre elevada e fachada imponente. É ponto de referência histórico, cultural e religioso para toda a comunidade.',
        historia: 'Edificada pelos colonos poloneses que chegaram à região no século XIX, a Igreja Matriz reflete a profunda fé e a dedicação artística dos imigrantes. Ao longo de mais de um século, passou por restaurações que preservaram seus elementos originais: vitrais coloridos, altar central e detalhes em madeira esculpida.',
        imagem: 'images/IGREJA_MATRIZ_FRONTAL.jpg',
        galeria: ['images/IGREJA_MATRIZ_FRONTAL.jpg', 'images/IGREJA_MATRIZ_1.png', 'images/IGREJA_MATRIZ_2.png'],
        endereco: 'Praça Rodrigues Alves, Centro — São Mateus do Sul, PR',
        horario: 'Missas: consulte a paróquia. Visitas externas: sempre disponível.',
        telefone: '(42) 3532-0000',
        site: null,
        instagram: null,
        facebook: null,
        lat: -25.8769,
        lng: -50.3838,
        mapsUrl: null,
        categoria: 'Patrimônio Histórico',
        rota: 'Turismo de Fé',
        acessibilidade: 'Acesso externo acessível. Consulte a paróquia para acesso interno.',
    },

    'igreja-agua-branca': {
        id: 'igreja-agua-branca',
        nome: 'Igreja São José — Comunidade da Água Branca',
        subtitulo: 'Patrimônio Polonês · Turismo de Fé',
        badge: '⛪ Cultura Polonesa',
        descricao: 'Considerada uma das mais belas igrejas rurais de herança polonesa do Paraná, a Igreja São José da Comunidade da Água Branca preserva intacta a arquitetura trazida pelos imigrantes do século XIX. Com lambrequins decorativos, interior colorido e um entorno rural de tirar o fôlego, é um dos pontos mais fotogênicos da região.',
        historia: 'Construída pelos descendentes poloneses que se estabeleceram na Localidade da Água Branca, a igreja foi erguida com técnicas e ornamentos típicos da arquitetura religiosa polonesa. Geração após geração, a comunidade manteve vivo o legado cultural através das celebrações, da arte sacra e da preservação do patrimônio.',
        imagem: 'images/IGREJA_AGUA_BRANCA.jpg',
        galeria: ['images/IGREJA_AGUA_BRANCA.jpg', 'images/IGREJA_AGUA_BRANCA_2.jpg', 'images/IGREJA_AGUA_BRANCA_3.jpg', 'images/IGREJA_AGUA_BRANCA_4.jpg', 'images/IGREJA_AGUA_BRANCA_5.jpg'],
        endereco: 'Localidade da Água Branca — São Mateus do Sul, PR',
        horario: 'Missas aos domingos. Visitas externas: sempre disponível.',
        telefone: null,
        site: null,
        instagram: null,
        facebook: null,
        lat: -25.9100,
        lng: -50.4200,
        mapsUrl: 'https://maps.app.goo.gl/uBoWdk',
        categoria: 'Patrimônio Histórico · Cultura Polonesa',
        rota: 'Rota Polonesa · Turismo de Fé',
        acessibilidade: 'Área rural. Acesso por estrada de terra.',
    },

    'rua-do-mathe': {
        id: 'rua-do-mathe',
        nome: 'Rua do Mathe',
        subtitulo: 'Gastronomia · Erva-Mate IG · Feiras',
        badge: '🧉 Erva-Mate IG',
        descricao: 'A Rua do Mathe é o coração gastronômico e cultural de São Mateus do Sul. Sede das principais feiras e festas da cidade, o espaço reúne produtores locais, restaurantes e a tradição da erva-mate com Indicação Geográfica IG São Matheus. Toda semana acontecem a Feira Gastronômica (quarta e sexta, 17h-22h) e a Feira do Produtor (sábados, 7h-12h).',
        historia: 'Batizada em homenagem ao chimarrão — bebida símbolo da identidade regional —, a Rua do Mathe foi criada para reunir e valorizar a produção local. Hoje é palco de festas tradicionais como a Polskie Smaki, o AgroSamas e inúmeros eventos culturais ao longo do ano.',
        imagem: 'images/WEBP/RUA-DO-MATHE-_1_.webp',
        galeria: ['images/WEBP/RUA-DO-MATHE-_1_.webp', 'images/WEBP/RUA-DO-MATHE-_1_-1.webp', 'images/WEBP/RUA-DO-MATHE-_2_.webp', 'images/RUA_DO_MATHE.jpg'],
        endereco: 'Rua do Mathe, Centro — São Mateus do Sul, PR',
        horario: 'Feira Gastronômica: Qua e Sex 17h-22h | Feira do Produtor: Sáb 7h-12h',
        telefone: '(42) 3532-4163',
        site: null,
        instagram: '@depculturaeturismosms',
        facebook: null,
        lat: -25.8780,
        lng: -50.3850,
        mapsUrl: null,
        categoria: 'Gastronomia · Cultura · Feiras',
        rota: 'Rota da Erva-Mate',
        acessibilidade: 'Espaço acessível.',
    },

    'praca-rio-iguacu': {
        id: 'praca-rio-iguacu',
        nome: 'Praça do Rio Iguaçu',
        subtitulo: 'Natureza · Lazer · Ponto Turístico',
        badge: '🌊 Natureza',
        descricao: 'A Praça do Rio Iguaçu é o principal espaço de lazer e contemplação da natureza em São Mateus do Sul. Com deck sobre o rio, playground, ciclovia e vista privilegiada para o Rio Iguaçu, o local atrai moradores e turistas em busca de contato com a natureza e tranquilidade. Também é sede do Chimarródromo, onde acontece a tradicional Roda de Mathe todo 1º domingo do mês.',
        historia: 'Localizada às margens do Rio Iguaçu, a praça representa a relação histórica da cidade com o rio que foi sua origem: um pouso de tropeiros às margens do Iguaçu no século XIX. O espaço foi revitalizado e hoje integra natureza, lazer e cultura em um único local.',
        imagem: 'images/WEBP/PRACA-DO-IGUACU_1.webp',
        galeria: ['images/WEBP/PRACA-DO-IGUACU_1.webp', 'images/PRACA_DO_RIO_IGUACU.jpg'],
        endereco: 'Rua João Gabriel Martins s/n — São Mateus do Sul, PR',
        horario: 'Aberto todos os dias. Roda de Mathe: 1º domingo do mês, 9h.',
        telefone: '(42) 3532-4163',
        site: null,
        instagram: '@depculturaeturismosms',
        facebook: null,
        lat: -25.8760,
        lng: -50.3855,
        mapsUrl: null,
        categoria: 'Natureza · Lazer',
        rota: 'Rota das Águas',
        acessibilidade: 'Espaço acessível com rampas.',
    },

    'prefeitura-municipal': {
        id: 'prefeitura-municipal',
        nome: 'Prefeitura Municipal',
        subtitulo: 'Patrimônio Histórico · Arquitetura',
        badge: '🏛️ Institucional',
        descricao: 'O edifício da Prefeitura Municipal de São Mateus do Sul é um exemplar da arquitetura do início do século XX que integra o patrimônio histórico do centro da cidade. Sua elegante fachada representa a tradição e a consolidação administrativa do município.',
        historia: 'Construído no século XX, o prédio da Prefeitura acompanhou o desenvolvimento da cidade desde os primeiros anos de sua emancipação. Ao longo das décadas, foi palco das decisões políticas e administrativas que moldaram São Mateus do Sul.',
        imagem: 'images/PREFEITURA_MUNICIPAL.jpg',
        galeria: ['images/PREFEITURA_MUNICIPAL.jpg'],
        endereco: 'Rua Barão do Rio Branco, Centro — São Mateus do Sul, PR',
        horario: 'Seg a Sex: 8h-12h e 13h-17h',
        telefone: '(42) 3532-0000',
        site: 'https://www.saomateusdosul.pr.gov.br',
        instagram: '@prefeiturasms',
        facebook: null,
        lat: -25.8775,
        lng: -50.3840,
        mapsUrl: null,
        categoria: 'Patrimônio Histórico',
        rota: 'Centro Histórico',
        acessibilidade: 'Acesso acessível pela entrada principal.',
    },

    'predio-historico': {
        id: 'predio-historico',
        nome: 'Prédio Histórico',
        subtitulo: 'Patrimônio · Centro Histórico',
        badge: '🏛️ Patrimônio',
        descricao: 'O centro histórico de São Mateus do Sul preserva edificações do início do século XX que testemunharam o crescimento da cidade. Os prédios históricos do entorno da praça central representam a arquitetura ecléctica e colonial que marca a identidade urbana da cidade.',
        historia: 'A ocupação do centro de São Mateus do Sul no início do século XX deixou um conjunto arquitetônico que reflete diferentes influências: polonesa, italiana e brasileira. Esses prédios são testemunhos da evolução econômica e cultural do município.',
        imagem: 'images/PREFEITURA_MUNICIPAL.jpg',
        galeria: ['images/PREFEITURA_MUNICIPAL.jpg'],
        endereco: 'Centro Histórico — São Mateus do Sul, PR',
        horario: 'Área pública. Acesso permanente.',
        telefone: '(42) 3532-0000',
        site: null,
        instagram: null,
        facebook: null,
        lat: -25.8775,
        lng: -50.3838,
        mapsUrl: null,
        categoria: 'Patrimônio Histórico',
        rota: 'Centro Histórico',
        acessibilidade: 'Área pública acessível.',
    },

    'casa-da-memoria': {
        id: 'casa-da-memoria',
        nome: 'Casa da Memória Padre Bauer',
        subtitulo: 'Museu · Memória · Patrimônio',
        badge: '🏛️ Museu',
        descricao: 'A Casa da Memória Padre Bauer é um espaço dedicado à preservação da memória histórica e cultural de São Mateus do Sul. Reúne acervo fotográfico, documentos e objetos que contam a história dos imigrantes poloneses e da formação do município.',
        historia: 'Homenagem ao Padre Bauer, figura fundamental na história religiosa e social da comunidade polonesa local, o espaço guarda a memória coletiva da cidade. Fotografias raras, documentos históricos e objetos do cotidiano dos colonos poloneses compõem um acervo único.',
        imagem: 'images/empreendimentos/casa-da-memoria/casa-da-memoria-01.jpeg',
        galeria: [
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-01.jpeg',
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-02.jpeg',
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-03.jpeg',
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-04.jpeg',
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-05.jpeg',
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-06.jpeg',
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-07.jpeg',
            'images/empreendimentos/casa-da-memoria/casa-da-memoria-08.jpeg'
        ],
        endereco: 'Centro — São Mateus do Sul, PR (confirmar endereço)',
        horario: 'Consulte o Departamento de Cultura e Turismo: (42) 3532-4163',
        telefone: '(42) 3532-4163',
        site: null,
        instagram: null,
        facebook: null,
        lat: -25.8770,
        lng: -50.3835,
        mapsUrl: null,
        categoria: 'Museu · Memória',
        rota: 'Cultura Polonesa · Centro Histórico',
        acessibilidade: 'Consulte disponibilidade.',
    },

    'paco-municipal': {
        id: 'paco-municipal',
        nome: 'Novo Paço Municipal',
        subtitulo: 'Administração · Patrimônio',
        badge: '🏛️ Institucional',
        descricao: 'O Paço Municipal de São Mateus do Sul é a sede administrativa do governo municipal, abrigando as secretarias e serviços públicos à população. Integra o conjunto histórico do centro da cidade.',
        historia: 'O Paço Municipal representa a modernização administrativa do município, centralizando os serviços públicos em um único espaço para melhor atender à população de São Mateus do Sul.',
        imagem: 'images/novo-paco-municipal.webp',
        galeria: ['images/novo-paco-municipal.webp'],
        endereco: 'Centro — São Mateus do Sul, PR',
        horario: 'Seg a Sex: 8h-12h e 13h-17h',
        telefone: '(42) 3532-0000',
        site: 'https://www.saomateusdosul.pr.gov.br',
        instagram: '@prefeiturasms',
        facebook: null,
        lat: -25.8776,
        lng: -50.3841,
        mapsUrl: null,
        categoria: 'Institucional',
        rota: 'Centro Histórico',
        acessibilidade: 'Acesso acessível.',
    },

    'chimarrodromo': {
        id: 'chimarrodromo',
        nome: 'Chimarródromo',
        subtitulo: 'Cultura · Erva-Mate IG · Tradição',
        badge: '🧉 Erva-Mate',
        descricao: 'O Chimarródromo é o espaço dedicado à valorização do chimarrão e da erva-mate com Indicação Geográfica de São Mateus do Sul. Todo primeiro domingo do mês, acontece a tradicional Roda de Mathe, com degustação gratuita da erva-mate local e confraternização comunitária.',
        historia: 'O chimarrão é parte inseparável da identidade de São Mateus do Sul, cidade reconhecida pela produção de erva-mate nativa (sombreada) com Indicação Geográfica IG São Matheus. O Chimarródromo surgiu como espaço dedicado a celebrar e difundir essa tradição centenária.',
        imagem: 'images/RUA_DO_MATHE.jpg',
        galeria: ['images/RUA_DO_MATHE.jpg'],
        endereco: 'Praça do Rio Iguaçu — São Mateus do Sul, PR',
        horario: 'Roda de Mathe: 1º domingo do mês, a partir das 9h. Entrada gratuita.',
        telefone: '(42) 3532-4163',
        site: null,
        instagram: '@depculturaeturismosms',
        facebook: null,
        lat: -25.8762,
        lng: -50.3856,
        mapsUrl: null,
        categoria: 'Cultura · Erva-Mate',
        rota: 'Rota da Erva-Mate',
        acessibilidade: 'Espaço acessível.',
    },

    'parque-exposicoes': {
        id: 'parque-exposicoes',
        nome: 'Parque de Exposições',
        subtitulo: 'Eventos · Agropecuária · Espaço multiuso',
        badge: '🚜 Agropecuária',
        descricao: 'O Parque de Exposições de São Mateus do Sul é um espaço destinado à realização de eventos de grande porte, exposições agropecuárias, shows e feiras.',
        historia: 'O Parque de Exposições foi construído para suprir a demanda por espaços adequados à realização de eventos de grande porte na cidade.',
        imagem: 'images/parque-exposicoes-aerea.webp',
        galeria: [
            'images/parque-exposicoes-aerea.webp',
            'images/WEBP/PARQUE-DE-EXPOSICOES-ARENA-DE-ESPORTES-PORTAL-POLONES-_4_.webp',
        ],
        endereco: 'São Mateus do Sul, PR (confirmar endereço)',
        horario: 'Varia conforme eventos. Consulte o calendário.',
        telefone: '(42) 3532-0000',
        site: null,
        instagram: '@prefeiturasms',
        facebook: null,
        lat: -25.8800,
        lng: -50.3900,
        mapsUrl: null,
        categoria: 'Eventos · Agropecuária',
        rota: 'Centro',
        acessibilidade: 'Consulte o evento específico.',
    },

    'arena-cultural': {
        id: 'arena-cultural',
        nome: 'Arena Cultural',
        subtitulo: 'Cultura · Shows · Eventos',
        badge: '🎭 Cultura',
        descricao: 'A Arena Cultural de São Mateus do Sul é um espaço destinado a shows, apresentações artísticas, espetáculos e eventos culturais da cidade. Sua utilização varia conforme a programação de cada evento.',
        historia: 'Concebida para democratizar o acesso à cultura, a Arena Cultural consolidou-se como um dos principais equipamentos culturais de São Mateus do Sul, recebendo atrações locais, regionais e nacionais.',
        imagem: 'images/WEBP/PARQUE-DE-EXPOSICOES-ARENA-DE-ESPORTES-PORTAL-POLONES-_5_.webp',
        galeria: ['images/WEBP/PARQUE-DE-EXPOSICOES-ARENA-DE-ESPORTES-PORTAL-POLONES-_5_.webp', 'images/WEBP/PARQUE-DE-EXPOSICOES-ARENA-DE-ESPORTES-PORTAL-POLONES-_6_.webp', 'images/WEBP/PARQUE-DE-EXPOSICOES-ARENA-DE-ESPORTES-PORTAL-POLONES-_7_.webp'],
        endereco: 'São Mateus do Sul, PR',
        horario: 'Varia conforme programação.',
        telefone: '(42) 3532-4163',
        site: null,
        instagram: '@depculturaeturismosms',
        facebook: null,
        lat: -25.8785,
        lng: -50.3860,
        mapsUrl: null,
        categoria: 'Cultura · Entretenimento',
        rota: 'Centro',
        acessibilidade: 'Consulte o evento específico.',
    },

    'ginasio-polacao': {
        id: 'ginasio-polacao',
        nome: 'Ginásio Polacão',
        subtitulo: 'Esporte · Eventos · Cultura',
        badge: '🏀 Esporte',
        descricao: 'O Ginásio Polacão é o principal espaço esportivo coberto de São Mateus do Sul. Além de sediar jogos e competições esportivas, o ginásio é utilizado para eventos culturais, feiras e celebrações de grande porte. Seu apelido carinhoso faz referência à herança polonesa da cidade.',
        historia: 'Batizado de "Polacão" em homenagem à cultura polonesa que define a identidade de São Mateus do Sul, o ginásio tornou-se referência esportiva e cultural para toda a região.',
        imagem: 'images/ginasio-polacao.webp',
        galeria: ['images/ginasio-polacao.webp'],
        endereco: 'São Mateus do Sul, PR',
        horario: 'Varia conforme programação.',
        telefone: '(42) 3532-0000',
        site: null,
        instagram: null,
        facebook: null,
        lat: -25.8790,
        lng: -50.3870,
        mapsUrl: null,
        categoria: 'Esporte · Cultura',
        rota: 'Centro',
        acessibilidade: 'Consulte disponibilidade.',
    },

    'ponte-rio-iguacu': {
        id: 'ponte-rio-iguacu',
        nome: 'Ponte do Rio Iguaçu',
        subtitulo: 'Cartão Postal · Natureza · Vista Panorâmica',
        badge: '🌊 Rio Iguaçu',
        descricao: 'A Ponte do Rio Iguaçu é o cartão postal de entrada de São Mateus do Sul. Vista do alto — especialmente em registros de drone —, ela revela a beleza ímpar da cidade sobre as margens do majestoso Rio Iguaçu. É um dos pontos mais fotografados e filmados da cidade.',
        historia: 'O Rio Iguaçu foi a razão da existência de São Mateus do Sul: um pouso de tropeiros às suas margens no século XIX originou o que hoje é a Capital Polonesa do Paraná. A ponte é o elo simbólico entre o passado histórico do rio e o presente da cidade.',
        imagem: 'images/WEBP/PONTE-ENTRADA-CIDADE-1-_2_.webp',
        galeria: ['images/WEBP/PONTE-ENTRADA-CIDADE-1-_2_.webp', 'images/WEBP/PONTE-ENTRADA-CIDADE-1-_3_.webp', 'images/PONTE_SOB_O_RIO_IGUACU.jpg'],
        endereco: 'Entrada de São Mateus do Sul — BR-476, PR',
        horario: 'Acesso permanente (via pública).',
        telefone: null,
        site: null,
        instagram: null,
        facebook: null,
        lat: -25.8700,
        lng: -50.3780,
        mapsUrl: null,
        categoria: 'Natureza · Cartão Postal',
        rota: 'Rota das Águas',
        acessibilidade: 'Via pública.',
    },

    'natal-ouro-verde': {
        id: 'natal-ouro-verde',
        nome: 'Natal Ouro Verde',
        subtitulo: 'Evento · Dezembro · Tradição',
        badge: '🎄 Evento',
        descricao: 'O Natal Ouro Verde é a maior festa de dezembro de São Mateus do Sul. Com desfiles temáticos, shows, iluminação especial, chegada do Papai Noel e feira gastronômica, o evento transforma o centro da cidade em um cenário mágico de fim de ano. Entrada gratuita.',
        historia: 'Criado para celebrar a época natalina com toda a identidade cultural de São Mateus do Sul, o Natal Ouro Verde incorpora a tradição polonesa ao espírito natalino. Ao longo dos anos, tornou-se um dos eventos mais esperados pela comunidade local e pelos turistas da região.',
        imagem: 'images/WEBP/NATAL-_17_.webp',
        galeria: ['images/WEBP/NATAL-_17_.webp', 'images/WEBP/NATAL-_18_.webp', 'images/WEBP/NATAL-_19_.webp', 'images/WEBP/NATAL-_20_.webp'],
        endereco: 'Centro da Cidade — São Mateus do Sul, PR',
        horario: '6 a 20 de dezembro de 2026. Consulte programação completa.',
        telefone: '(42) 3532-4163',
        site: null,
        instagram: '@depculturaeturismosms',
        facebook: null,
        lat: -25.8775,
        lng: -50.3840,
        mapsUrl: null,
        categoria: 'Eventos · Tradição',
        rota: 'Eventos Anuais',
        acessibilidade: 'Espaço público acessível.',
    },

    'miss-sao-mateus': {
        id: 'miss-sao-mateus',
        nome: 'Miss São Mateus do Sul',
        subtitulo: 'Evento · Cultura · Tradição',
        badge: '👑 Evento',
        descricao: 'O Miss São Mateus do Sul é um concurso de beleza e cultura que celebra a identidade polonesa e a diversidade da cidade. As candidatas representam as diferentes comunidades e localidades do município, e o evento integra a programação de festas tradicionais como a Polskie Smaki.',
        historia: 'Tradição que atravessa décadas, o Miss São Mateus do Sul é mais do que um concurso de beleza: é uma celebração da identidade cultural da cidade, especialmente da herança polonesa que define seu povo.',
        imagem: 'images/POLSKIE_SMAKI__1_.jpg',
        galeria: ['images/POLSKIE_SMAKI__1_.jpg'],
        endereco: 'São Mateus do Sul, PR',
        horario: 'Varia conforme programação anual.',
        telefone: '(42) 3532-4163',
        site: null,
        instagram: '@depculturaeturismosms',
        facebook: null,
        lat: -25.8775,
        lng: -50.3840,
        mapsUrl: null,
        categoria: 'Eventos · Cultura',
        rota: 'Eventos Anuais',
        acessibilidade: 'Consulte o local do evento.',
    },

};

/**
 * Aliases de compatibilidade: slug legado → id canônico.
 * Mantém funcionando links antigos sem duplicar dados nem poluir Object.keys(locaisData).
 * 'casa-memoria-padre-bauer' foi o id usado no Bloco S8; o id canônico passou a ser
 * 'casa-da-memoria' (alinhado à fonte primária js/data/pontos-turisticos.js e à pasta
 * de imagens images/empreendimentos/casa-da-memoria/).
 */
const locaisAliases = {
    'casa-memoria-padre-bauer': 'casa-da-memoria',
};

// Exporta para uso global
window.locaisData = locaisData;
window.locaisAliases = locaisAliases;
