// ============================================================
// rotas-data.js — Camada de dados dos empreendimentos turísticos
// São Mateus do Sul — Rotas Rurais
// Coordenadas resolvidas via redirect de maps.app.goo.gl
// ============================================================

const routeInfo = {
    sabores:  { icon: '🍓', name: 'Sabores & Memórias',      color: '#c0392b' },
    mate:     { icon: '🌿', name: 'Rota da Erva-Mate',       color: '#27ae60' },
    polonesa: { icon: '⛪', name: 'Rota Polonesa',            color: '#2980b9' },
    aguas:    { icon: '🌊', name: 'Rota das Águas',           color: '#0891b2' },
    fluviop:  { icon: '🏘️', name: 'Caminhos de Fluviópolis', color: '#d97706' },
    terra:    { icon: '🌱', name: 'Rota da Terra',            color: '#65a30d' }
};

const establishments = [

    // ── ROTA SABORES & MEMÓRIAS ─────────────────────────────
    {
        id: 'morangos-da-mary',
        route: 'sabores',
        name: 'Morangos da Mary',
        subtitle: 'Sabor que adoça a vida',
        desc: 'Experiência "colha e pague" de morangos com manejo biológico e sustentável.',
        location: 'Localidade de Divisa',
        phone: '(42) 99820-6671',
        hours: 'Sáb e Dom 14h30–18h; Seg–Sex com agendamento',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/GZDc2rnRxA6jBap97',
        lat: -25.9838616,
        lng: -50.3783231,
        coordStatus: 'ok'
    },
    {
        id: 'dalety',
        route: 'sabores',
        name: 'Dalety — Queijos e Doces',
        subtitle: 'Doces, Queijos e Memórias Tropeiras',
        desc: 'Café colonial com 6 tipos de queijos artesanais, pães, bolachas e doces caseiros.',
        location: 'Localidade de Divisa',
        phone: '(42) 99875-2822',
        hours: 'Um domingo por mês (agendamento prévio)',
        social: '@dalety_queijosedoces',
        mapsUrl: 'https://maps.app.goo.gl/395K6fVUNkBcEAAb7',
        lat: -26.0749028,
        lng: -50.3412974,
        coordStatus: 'ok'
    },
    {
        id: 'all-garden',
        route: 'sabores',
        name: 'All Garden',
        subtitle: 'Memórias Inesquecíveis',
        desc: 'Trilhas, rio, buffet e cestas de piquenique em meio à natureza.',
        location: 'Localidade de Divisa',
        phone: '(42) 99813-2267',
        hours: 'Terça a domingo (agendamento prévio)',
        social: '@allgardenmoments',
        mapsUrl: 'https://maps.app.goo.gl/16iaXV4UngbR8ojD6',
        lat: -26.041454,
        lng: -50.334855,
        coordStatus: 'ok'
    },
    {
        id: 'nova-esperanca',
        route: 'sabores',
        name: 'Nova Esperança',
        subtitle: 'Centro de Equoterapia e Equitação',
        desc: 'Passeios a cavalo, equoterapia e conexão com animais. Espaço inclusivo.',
        location: 'Localidade de Divisa',
        phone: '(42) 99903-1325',
        hours: 'Seg–Sex 9h–18h; Sáb e Dom com agendamento',
        social: '@novaesperanca.equoterapia',
        mapsUrl: 'https://maps.app.goo.gl/aYhiSqn2HuMRVjPPA',
        lat: -26.0718031,
        lng: -50.3450588,
        coordStatus: 'ok'
    },
    {
        id: 'cabana-campo-de-telha',
        route: 'sabores',
        name: 'Cabana Campo de Telha',
        subtitle: 'Museu da cultura tropeira',
        desc: 'Museu autoguiado com utensílios e objetos do tropeirismo paranaense. Modas de viola.',
        location: 'Localidade de Divisa',
        phone: '(42) 99927-6171',
        hours: 'Sáb e Dom 13h–17h (agendamento prévio)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/crK2PUe93CNRPr989',
        lat: -26.0650985,
        lng: -50.3452197,
        coordStatus: 'ok'
    },

    // ── ROTA DA ERVA-MATE ───────────────────────────────────
    {
        id: 'ervateira-rei-verde',
        route: 'mate',
        name: 'Ervateira Rei Verde',
        subtitle: 'Uma imersão completa no mundo da erva-mate',
        desc: 'Visita guiada ao cultivo, colheita e industrialização. Degustação e chimarrão.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 3560-1128',
        hours: 'Segunda a sexta (agendamento)',
        social: '@ervamatereiverde',
        mapsUrl: 'https://maps.app.goo.gl/cZvq9UMcGCUCAdph8',
        lat: -26.0153052,
        lng: -50.6259214,
        coordStatus: 'ok'
    },
    {
        id: 'ervateira-baldo',
        route: 'mate',
        name: 'Baldo S/A Comércio, Indústria e Exportação',
        subtitle: 'Indústria de erva-mate',
        desc: 'Indústria de erva-mate na BR-476, com tradição no beneficiamento e exportação. Atendimento e visitação sob consulta com a empresa.',
        location: 'BR-476, Km 285 — Colônia Iguaçu, São Mateus do Sul/PR, CEP 83905-060',
        phone: '(42) 3520-1100 / (42) 98815-7391',
        hours: 'Horário e visitação sob consulta',
        social: '@matebaldo',
        mapsUrl: 'https://maps.app.goo.gl/ebTHTCucyfKG8biE8',
        lat: -25.907978,
        lng: -50.4431114,
        coordStatus: 'ok'
    },
    {
        id: 'parada-do-chimarrao',
        route: 'mate',
        routes: ['mate', 'fluviop'],
        name: 'Parada do Chimarrão',
        subtitle: 'Tradição da erva-mate e cultura do chimarrão',
        desc: 'Aprenda a preparar chimarrão, decore cuias e descubra artesanato local.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 99960-0496',
        hours: 'Segunda a sábado 7h30–19h',
        social: '@paradadochimarrao476',
        mapsUrl: 'https://maps.app.goo.gl/QjXCfjBUFiteu9FJA',
        lat: -25.9997023,
        lng: -50.5898926,
        coordStatus: 'ok'
    },
    {
        id: 'ervateira-taquaral',
        route: 'mate',
        name: 'Ervateira Taquaral',
        subtitle: 'Da sombra das araucárias diretamente para sua cuia',
        desc: 'Tradição familiar desde 1994. Visita ao cultivo e fábrica, degustação.',
        location: 'Localidade de Taquaral do Bugre',
        phone: '(42) 98834-0858',
        hours: 'Sob agendamento',
        social: '@ervamatetaquaral',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Ervateira+Taquaral+Taquaral+do+Bugre+Sao+Mateus+do+Sul+PR',
        lat: -25.82,
        lng: -50.35,
        coordStatus: 'aproximada',
        coordNote: 'O PDF repete o link da Parada do Chimarrão; por enquanto o mapa usa uma posição aproximada em Taquaral do Bugre.'
    },
    {
        id: 'vivenda-do-mate',
        route: 'mate',
        name: 'Vivenda do Mate',
        subtitle: 'O mate além da cuia',
        desc: 'Cinco gerações de tradição. Sapeco, trilhas, chimarrão, drinks e doces de erva-mate.',
        location: 'Localidade do Faxinal do Ilhéus',
        phone: '(41) 99844-8547',
        hours: 'Sob agendamento',
        social: '@vivendadomate',
        mapsUrl: 'https://maps.app.goo.gl/aGsuK1gx27gTcvic8',
        lat: -25.796941,
        lng: -50.3619338,
        coordStatus: 'ok'
    },
    {
        id: 'viveiro-santana',
        route: 'mate',
        routes: ['mate', 'terra'],
        name: 'Viveiro Santana',
        subtitle: 'Vivencie a tradição e o cuidado na produção da erva-mate',
        desc: 'Processo produtivo completo da erva-mate, do cultivo à colheita.',
        location: 'Localidade do Lajeadinho',
        phone: '(42) 99964-2230',
        hours: 'Qualquer dia com agendamento',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/GZk8LAKXVZkgFAbn7',
        lat: -25.8958135,
        lng: -50.255742,
        coordStatus: 'ok'
    },
    {
        id: 'bierherr',
        route: 'mate',
        name: 'BierHerr',
        subtitle: 'Cervejaria artesanal com cerveja premiada à base de erva-mate',
        desc: 'Visita técnica guiada e degustação de cerveja artesanal premiada com erva-mate.',
        location: 'Bairro São Joaquim',
        phone: '(42) 99934-3798',
        hours: '1ª segunda-feira do mês a partir das 13h (agendamento)',
        social: '@bierherr',
        mapsUrl: 'https://maps.app.goo.gl/iev6kghuzjegwvLN8',
        lat: -25.8675163,
        lng: -50.39865,
        coordStatus: 'ok'
    },

    // ── ROTA POLONESA ────────────────────────────────────────
    {
        id: 'igreja-agua-branca',
        route: 'polonesa',
        name: 'Igreja Centenária da Água Branca',
        subtitle: 'Imersão nas tradições culturais e religiosas da imigração',
        desc: 'Café da manhã, histórias, Coral Karolinka e dança polonesa. Celebração mensal dia 26.',
        location: 'Localidade da Água Branca',
        phone: '(42) 98812-4513',
        hours: 'Sábados e domingos (sob agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/uBoWdkPR5Q4BRLMo9',
        lat: -25.7629092,
        lng: -50.3425659,
        coordStatus: 'ok'
    },
    {
        id: 'delicias-da-bernardina',
        route: 'polonesa',
        name: 'Delícias da Bernardina',
        subtitle: 'Culinária Polonesa',
        desc: 'Almoço ou jantar típico polonês, oficinas de culinária. Até 90 pessoas.',
        location: 'Colônia Taquaral',
        phone: '(42) 98845-7103',
        hours: 'Domingo a domingo (sob agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/4eRtLvxAhKhc9mZYA',
        lat: -25.8243901,
        lng: -50.3306747,
        coordStatus: 'ok'
    },
    {
        id: 'armazem-campestre',
        route: 'polonesa',
        name: 'Armazém Campestre',
        subtitle: 'Histórias e delícias da roça',
        desc: 'Armazém histórico (70 anos). Pães artesanais, defumados, forno a lenha e objetos antigos.',
        location: 'Localidade do Espigãozinho',
        phone: '(42) 98842-6131',
        hours: 'Domingo a domingo (sob agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/Ueeh6eP6NQf4hfD66',
        lat: -25.8188137,
        lng: -50.3281576,
        coordStatus: 'ok'
    },
    {
        id: 'queijos-cleonice',
        route: 'polonesa',
        name: 'Queijos Artesanais da Cleonice',
        subtitle: 'Queijos artesanais com sabor e identidade',
        desc: 'Seis variedades de queijo artesanal: vinho, defumado, parmesão, provolone, temperado e meia cura.',
        location: 'Colônia Taquaral',
        phone: '(42) 98824-2769',
        hours: 'Domingo a domingo (sob agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/xziqeq4ycDTVWhvq9',
        lat: -25.8045548,
        lng: -50.3359162,
        coordStatus: 'ok'
    },
    {
        id: 'prop-ines-lucival',
        route: 'polonesa',
        name: 'Propriedade da Inês e do Lucival',
        subtitle: 'Colheita de Uva',
        desc: 'Colheita da uva Poloski (variedade polonesa rara). Parreirais, banana e erva-mate.',
        location: 'Localidade de Espigãozinho',
        phone: '(42) 99813-9448',
        hours: 'Dezembro e janeiro (sob agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/LJz4FR3GxwBnQHmV8',
        lat: -25.8002809,
        lng: -50.320823,
        coordStatus: 'ok'
    },
    {
        id: 'ancestral-gastronomia',
        route: 'polonesa',
        name: 'Ancestral Gastronomia',
        subtitle: 'Sabores que atravessam gerações',
        desc: 'Culinária polonesa, pães de fermentação natural e eventos temáticos.',
        location: 'Colônia Taquaral',
        phone: '(42) 98804-0535',
        hours: 'Sob agendamento',
        social: '@ancestral.gastronomia',
        mapsUrl: 'https://maps.app.goo.gl/qWHHg8zm62Xyfsc29',
        lat: -25.8465617,
        lng: -50.3827306,
        coordStatus: 'ok'
    },
    {
        id: 'artur-biergarten',
        route: 'polonesa',
        name: 'Artur Biergarten',
        subtitle: 'Um toque alemão na Rota Polonesa',
        desc: 'Almoço com culinária alemã, chopp artesanal, colheita de mirtilo e campo de girassóis.',
        location: 'Localidade do Faxinal do Ilhéus',
        phone: '(42) 98418-1639',
        hours: 'Sob agendamento',
        social: '@artur.biergarten',
        mapsUrl: 'https://maps.app.goo.gl/2aXN1YXLGXNYRj4q6',
        lat: -25.8392794,
        lng: -50.3644773,
        coordStatus: 'ok'
    },

    // ── ROTA DAS ÁGUAS ──────────────────────────────────────
    {
        id: 'ribeiro-pesca',
        route: 'aguas',
        name: 'Ribeiro Pesca e Turismo',
        subtitle: 'Pesca esportiva e passeio fluvial',
        desc: 'Passeio pelo Rio Iguaçu e pesca esportiva com orientação de especialistas.',
        location: 'Centro — Praça do Rio Iguaçu',
        phone: '(42) 99804-0096',
        hours: 'Todo domingo a partir das 14h',
        social: '@ribeiropescaeturismo',
        mapsUrl: 'https://maps.app.goo.gl/WvvnT3ujrbA5T6t5A',
        lat: -25.8767299,
        lng: -50.3860571,
        coordStatus: 'ok'
    },
    {
        id: 'marina-barra-iguacu',
        route: 'aguas',
        name: 'Marina Barra do Iguaçu',
        subtitle: 'Centro Náutico de Água Doce',
        desc: 'Restaurante de frutos do mar, Centro Náutico e lazer à beira-rio.',
        location: 'Colônia Iguaçu',
        phone: '(42) 98841-6009',
        hours: 'Qua–Sex 16h–23h; Sáb e Dom 11h30–17h',
        social: '@marina.barradoiguacu',
        mapsUrl: 'https://maps.app.goo.gl/yNfddeGwUY1peEr89',
        lat: -25.8899745,
        lng: -50.4340955,
        coordStatus: 'ok'
    },
    {
        id: 'ulbrich',
        route: 'aguas',
        routes: ['aguas', 'fluviop'],
        name: 'Área de Lazer Ulbrich',
        subtitle: 'Lazer, esportes e descanso às margens do Rio Potinga',
        desc: 'Casas para locação, piscinas, pesca e almoços às margens do Rio Potinga.',
        location: 'Localidade da Barra do Potinga',
        phone: '(42) 98808-3565',
        hours: 'Dom a Dom (locação); Almoço domingos Abr–Nov',
        social: '@ulbrichareadelazer',
        mapsUrl: 'https://maps.app.goo.gl/STbUjrHbNiVbFtFM8',
        lat: -25.9952367,
        lng: -50.5206071,
        coordStatus: 'ok'
    },
    {
        id: 'pesqueiro-tio-ivo',
        route: 'aguas',
        routes: ['aguas', 'fluviop'],
        name: 'Pesqueiro Tio Ivo',
        subtitle: 'Tranquilidade e momentos marcantes',
        desc: 'Pesque e pague, pedalinho, campo de futebol e churrasqueira.',
        location: 'Localidade do Emboque',
        phone: '(42) 99829-9245',
        hours: 'Sáb, Dom e Feriados 9h–21h',
        social: '@pesqueirotioivo2024',
        mapsUrl: 'https://maps.app.goo.gl/R3pbCcKr1NYqt82G6',
        lat: -25.9114928,
        lng: -50.4542586,
        coordStatus: 'ok'
    },
    {
        id: 'pesqueiro-da-joana',
        route: 'aguas',
        routes: ['aguas', 'fluviop'],
        name: 'Pesqueiro da Joana',
        subtitle: 'Conforto e pesca às margens do Rio Iguaçu',
        desc: 'Pesca de barranco, camping, quiosque, casas para locação e parquinho.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98805-6204',
        hours: 'Terça a domingo 8h–22h',
        social: '@pesqueirodajoana',
        mapsUrl: 'https://maps.app.goo.gl/29S9akQkEG2kTSpC7',
        lat: -26.0485231,
        lng: -50.5893005,
        coordStatus: 'ok'
    },
    {
        id: 'pesqueiro-do-luizao',
        route: 'aguas',
        routes: ['aguas', 'fluviop'],
        name: 'Pesqueiro do Luizão',
        subtitle: 'Pesca, descanso e história à beira do Rio Iguaçu',
        desc: 'Pesca, camping, hospedagem familiar, churrasqueiras e artesanato em ferro.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 99911-1031',
        hours: 'Domingo a domingo 8h–23h',
        social: '@pesqueiro._do_.luizao',
        mapsUrl: 'https://maps.app.goo.gl/qcm4tVTkr6QaGQK89',
        lat: -26.0095864,
        lng: -50.582548,
        coordStatus: 'ok'
    },
    {
        id: 'pesqueiro-do-kiko',
        route: 'aguas',
        routes: ['aguas', 'fluviop'],
        name: 'Pesqueiro do Kiko',
        subtitle: 'Pesca e belas paisagens',
        desc: 'Pesca de barranco, pesca no rio e área de camping.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98873-6812',
        hours: 'Domingo a domingo 8h–23h',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/sZfDG5tViw6evqFz7',
        lat: -26.000956,
        lng: -50.5678445,
        coordStatus: 'ok'
    },
    {
        id: 'rancho-samas',
        route: 'aguas',
        name: 'Rancho Samas',
        subtitle: 'Pesque e pague e restaurante',
        desc: 'Pesque e pague, almoço em datas especiais e porções.',
        location: 'Colônia Cachoeira',
        phone: '(42) 99976-9967',
        hours: 'Terça a domingo 10h–20h',
        social: '@ranchosamas',
        mapsUrl: 'https://maps.app.goo.gl/mZoHcAoL5wdEfjgb7',
        lat: -25.8654225,
        lng: -50.4458589,
        coordStatus: 'ok'
    },
    {
        id: 'pesqueiro-do-pedrao',
        route: 'aguas',
        routes: ['aguas', 'fluviop'],
        name: 'Pesqueiro do Pedrão',
        subtitle: 'Empreendimento potencial',
        desc: 'Pesqueiro citado no material oficial do turismo rural e em fase de detalhamento para atendimento ao visitante.',
        location: 'Localidade de Fluviópolis',
        phone: '',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Pesqueiro+do+Pedrao+Fluviopolis+Sao+Mateus+do+Sul+PR',
        lat: -25.9718696,
        lng: -50.5267363,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região de Fluviópolis até a validação final.'
    },

    // ── ROTA CAMINHOS DE FLUVIÓPOLIS ────────────────────────
    {
        id: 'frigorifico-3m',
        route: 'fluviop',
        name: 'Frigorífico 3M — Casa de Carnes',
        subtitle: 'Carne de cordeiro de alta qualidade',
        desc: 'Carnes nobres de cordeiro de genética premiada. Mais de duas décadas de tradição.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98829-5002',
        hours: 'Segunda a sábado 8h–18h',
        social: '@frigorifico_3m_carnes_nobres',
        mapsUrl: 'https://maps.app.goo.gl/fGEHwX3zid9jjCSQ6',
        lat: -25.9776365,
        lng: -50.5510423,
        coordStatus: 'ok'
    },
    {
        id: 'canil-sao-jose',
        route: 'fluviop',
        name: 'Canil e CT São José',
        subtitle: 'Tradição, treinamento e paixão por cães de pastoreio',
        desc: 'Demonstração de pastoreio com Border Collies. Hotel e creche pet.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98819-8950',
        hours: 'Segunda a domingo (por agendamento)',
        social: '@ctecanilsaojose06',
        mapsUrl: 'https://maps.app.goo.gl/zdU9Gs6mEiEpJqL47',
        lat: -25.9454181,
        lng: -50.5545948,
        coordStatus: 'ok'
    },
    {
        id: 'parada-pinoli',
        route: 'fluviop',
        name: 'Parada Pinoli',
        subtitle: 'Pausa necessária',
        desc: 'Restaurante, panificação fresquinha, espaço pet e kids na estrada.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 99960-0496',
        hours: 'Segunda a domingo 8h–22h',
        social: '@paradapinoli',
        mapsUrl: 'https://maps.app.goo.gl/uPh85sFEXPU1W7GLA',
        lat: -25.9989864,
        lng: -50.5866816,
        coordStatus: 'ok'
    },
    {
        id: 'hotel-moro',
        route: 'fluviop',
        name: 'Hotel Moro',
        subtitle: 'Descanso revigorante',
        desc: 'Hospedagem confortável com café da manhã e estacionamento gratuito.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98887-4202',
        hours: '24h (domingo a domingo)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/6Tq13bQXziJGpwzw9',
        lat: -25.9980108,
        lng: -50.5880208,
        coordStatus: 'ok'
    },
    {
        id: 'churrascaria-dallas',
        route: 'fluviop',
        name: 'Restaurante e Churrascaria Dallas',
        subtitle: 'Delícias na estrada',
        desc: 'Buffet variado, carnes selecionadas, saladas frescas e sobremesas caseiras.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98845-6741',
        hours: 'Segunda a sábado 8h–20h',
        social: '@dallas_restaurante11',
        mapsUrl: 'https://maps.app.goo.gl/mSXYXC1FAaeH1Skz5',
        lat: -25.9572075,
        lng: -50.5168741,
        coordStatus: 'ok'
    },
    {
        id: 'prop-eduardo-pachek',
        route: 'fluviop',
        name: 'Propriedade Eduardo Pachek',
        subtitle: 'Sabores da uva direto do parreiral',
        desc: 'Visita ao parreiral, colheita e degustação de uva branca, rosada e bordô.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98826-4420',
        hours: 'Janeiro 8h–18h (agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/MpA2ixAJx81j4MiN9',
        lat: -25.918795,
        lng: -50.441716,
        coordStatus: 'ok'
    },
    {
        id: 'pitayas-dragao',
        route: 'fluviop',
        name: 'Pitayas Dragão do Iguaçu',
        subtitle: 'Frutas, mudas e conhecimento no campo',
        desc: 'Mais de 400 pés de pitaya. Colheita, degustação e venda de mudas.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98875-2708',
        hours: 'Fins de semana Jan–Abr (agendamento)',
        social: '@pitayasdragaodoiguacu',
        mapsUrl: 'https://maps.app.goo.gl/ou9JKXgPQGvRnMfX7',
        lat: -25.9660091,
        lng: -50.5398216,
        coordStatus: 'aproximada',
        coordNote: 'O link do Google Maps abre corretamente, mas sem coordenada numérica estável; o mapa usa uma posição aproximada em Fluviópolis.'
    },
    {
        id: 'posto-pelanda',
        route: 'fluviop',
        name: 'Posto Pelanda',
        subtitle: 'Empreendimento potencial',
        desc: 'Ponto de apoio rodoviário citado no material oficial da Rota Caminhos de Fluviópolis.',
        location: 'BR-476 — Comunidade Potinga / Fluviópolis',
        phone: '(41) 99701-7327',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Posto+Pelanda+Fluviopolis+Sao+Mateus+do+Sul+PR',
        lat: -25.9660091,
        lng: -50.5398216,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região de Fluviópolis até a validação final.'
    },
    {
        id: 'viveiro-fluviopolis',
        route: 'fluviop',
        name: 'Viveiro Fluviópolis',
        subtitle: 'Empreendimento potencial',
        desc: 'Viveiro citado no material oficial da Rota Caminhos de Fluviópolis e pendente de detalhamento complementar.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98811-4104',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Viveiro+Fluviopolis+Sao+Mateus+do+Sul+PR',
        lat: -25.9660091,
        lng: -50.5398216,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região de Fluviópolis até a validação final.'
    },
    {
        id: 'prop-seu-luiz',
        route: 'fluviop',
        name: 'Propriedade do Seu Luiz',
        subtitle: 'Empreendimento potencial',
        desc: 'Propriedade rural mencionada no material oficial da rota e ainda em fase de validação de dados públicos.',
        location: 'Localidade de Fluviópolis',
        phone: '',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Propriedade+do+Seu+Luiz+Fluviopolis+Sao+Mateus+do+Sul+PR',
        lat: -25.9660091,
        lng: -50.5398216,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região de Fluviópolis até a validação final.'
    },
    {
        id: 'sitio-pica-pau-vermelho',
        route: 'fluviop',
        name: 'Sítio Pica-pau Vermelho',
        subtitle: 'Empreendimento potencial',
        desc: 'Sítio citado no material oficial da Rota Caminhos de Fluviópolis e mantido em validação para inclusão completa.',
        location: 'Localidade de Fluviópolis',
        phone: '',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sitio+Pica-pau+Vermelho+Fluviopolis+Sao+Mateus+do+Sul+PR',
        lat: -25.9660091,
        lng: -50.5398216,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região de Fluviópolis até a validação final.'
    },

    // ── ROTA DA TERRA ────────────────────────────────────────
    {
        id: 'viveiro-mk',
        route: 'terra',
        name: 'Viveiro MK',
        subtitle: 'Cultivando a vida, entre cores e perfumes',
        desc: 'Mudas, flores, orquídeas, cestas e arranjos. Visita guiada para grupos.',
        location: 'Localidade da Vargem Grande',
        phone: '(42) 99811-3366',
        hours: 'Viveiro Seg–Sex 8h–18h; Loja Sáb 8h–13h',
        social: '@lojaviveiromk',
        mapsUrl: 'https://maps.app.goo.gl/8Dm2XgjeRzsADBEE6',
        lat: -25.9069002,
        lng: -50.2895654,
        coordStatus: 'ok'
    },
    {
        id: 'sawe-parque',
        route: 'terra',
        routes: ['terra', 'aguas'],
        name: 'Sawe Parque Aquático',
        subtitle: 'Um refúgio de lazer e diversão para todas as idades',
        desc: 'Day use com piscina, toboágua, pedalinho, tirolesa e casas para locação.',
        location: 'Localidade da Vargem Grande',
        phone: '(42) 99975-7499',
        hours: 'Segunda a domingo 9h–19h',
        social: '@parquesawe',
        mapsUrl: 'https://maps.app.goo.gl/SBiV96sKr26nntj17',
        lat: -25.9109781,
        lng: -50.2996864,
        coordStatus: 'ok'
    },
    {
        id: 'mag-verduras',
        route: 'terra',
        name: 'Mag Verduras',
        subtitle: 'Sabores da terra e café',
        desc: 'Horta orgânica, sacolas colhidas na hora e café rural com iguarias caseiras.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98845-2124',
        hours: 'Segunda a domingo (por agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/9vesRN5WoBJVw7XE6',
        lat: -25.895942,
        lng: -50.258702,
        coordStatus: 'ok'
    },
    {
        id: 'prop-do-tico',
        route: 'terra',
        name: 'Propriedade do Tico',
        subtitle: 'Venda de produtos, sementes e mudas',
        desc: 'Guardião de sementes, produção orgânica agroecológica. Práticas biodinâmicas.',
        location: 'Localização em validação',
        phone: '(42) 98807-7985',
        hours: 'Sábados e domingos (por agendamento)',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Propriedade+do+Tico+Sao+Mateus+do+Sul+PR',
        lat: -25.9023988,
        lng: -50.2760447,
        coordStatus: 'aproximada',
        coordNote: 'O PDF marca a localização como "Verificar"; o mapa usa uma posição aproximada na região da Rota da Terra até a validação final.'
    },
    {
        id: 'sitio-sapopema',
        route: 'terra',
        name: 'Sítio Sapopema',
        subtitle: 'Sabor, agroecologia e artesanato no campo',
        desc: 'Certificação orgânica ECOVIDA. Pão no bafo (tigrão) e almoço rural.',
        location: 'Localização em validação',
        phone: '(42) 98869-8709',
        hours: 'Qualquer dia (sob agendamento)',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sitio+Sapopema+Sao+Mateus+do+Sul+PR',
        lat: -25.9023988,
        lng: -50.2760447,
        coordStatus: 'aproximada',
        coordNote: 'O PDF marca a localização como "Verificar"; o mapa usa uma posição aproximada na região da Rota da Terra até a validação final.'
    },
    {
        id: 'prop-da-sabrina',
        route: 'terra',
        name: 'Propriedade da Sabrina',
        subtitle: 'Sabores do tropeirismo',
        desc: 'Coxinha de farofa tradicional. Aceita encomendas para festas e eventos.',
        location: 'Localidade de Fluviópolis',
        phone: '(42) 98890-7686',
        hours: 'Qualquer dia (sob agendamento)',
        social: '',
        mapsUrl: 'https://maps.app.goo.gl/XDSNFxXJSh3tkQRHA',
        lat: -25.895775,
        lng: -50.256225,
        coordStatus: 'ok'
    },
    {
        id: 'prop-antonia-gabriel',
        route: 'terra',
        name: 'Propriedade da Antonia e Gabriel',
        subtitle: 'Empreendimento potencial',
        desc: 'Propriedade rural listada como potencial no material oficial da Rota da Terra.',
        location: 'Localização em validação',
        phone: '',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Propriedade+da+Antonia+e+Gabriel+Sao+Mateus+do+Sul+PR',
        lat: -25.9023988,
        lng: -50.2760447,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região da Rota da Terra até a validação final.'
    },
    {
        id: 'prop-do-beto',
        route: 'terra',
        name: 'Propriedade do Beto',
        subtitle: 'Empreendimento potencial',
        desc: 'Propriedade rural citada no material oficial da Rota da Terra, com referência à região de Vista Alegre.',
        location: 'Vista Alegre',
        phone: '(42) 98828-6195',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Propriedade+do+Beto+Vista+Alegre+Sao+Mateus+do+Sul+PR',
        lat: -25.9023988,
        lng: -50.2760447,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região da Rota da Terra até a validação final.'
    },
    {
        id: 'sitio-ludevico',
        route: 'terra',
        name: 'Sítio Ludevico',
        subtitle: 'Empreendimento potencial',
        desc: 'Sítio mencionado como potencial no material oficial da Rota da Terra.',
        location: 'Vista Alegre',
        phone: '(42) 98839-5278',
        hours: 'Empreendimento potencial em validação',
        social: '',
        mapsUrl: 'https://www.google.com/maps/search/?api=1&query=Sitio+Ludevico+Vista+Alegre+Sao+Mateus+do+Sul+PR',
        lat: -25.9023988,
        lng: -50.2760447,
        coordStatus: 'aproximada',
        coordNote: 'Listado como empreendimento potencial no PDF; o mapa usa uma posição aproximada na região da Rota da Terra até a validação final.'
    }
];
