/* CRUD local/Emulator de Rotas V1.1. Relacoes vivem somente em cms_establishments.relationships.routeIds[]. */
(function () {
    "use strict";
    if (window.AdminRoutesModule || !window.AdminRoutesHelpers) return;
    var H = window.AdminRoutesHelpers, SECTION_ID = "rotas", ROUTES = "rotas", ESTABLISHMENTS = "cms_establishments";
    var state = { items: [], establishments: [], media: [], loading: false, saving: false, error: "", filterStatus: "all", query: "", selectedId: "", selectedEstablishmentIds: [], pendingForm: null };
    function db() { return window.AdminContext && window.AdminContext.db; }
    function uid() { var user = window.AdminContext && window.AdminContext.currentUser; return user && user.role === "admin" && user.ativo === true ? user.uid : ""; }
    function ts() { return window.firebase && window.firebase.firestore ? window.firebase.firestore.FieldValue.serverTimestamp() : null; }
    function esc(value) { return window.AdminUI ? window.AdminUI.escapeHtml(value) : H.clean(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;"); }
    function js(value) { return H.clean(value).replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/\r/g,"\\r").replace(/\n/g,"\\n").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;"); }
    function toast(message, type) { return window.AdminUI && window.AdminUI.showToast ? window.AdminUI.showToast(message, type) : null; }
    function section() { return document.getElementById("section-" + SECTION_ID); }
    function modal(title, html) { if (window.AdminContentCMS && window.AdminContentCMS.openModal) return window.AdminContentCMS.openModal(title, html); }
    function closeModal() { if (window.AdminContentCMS && window.AdminContentCMS.closeModal) window.AdminContentCMS.closeModal(); }
    function activeAdmin() { if (uid()) return true; toast("Apenas administradores ativos podem alterar Rotas.", "error"); return false; }
    function statusLabel(status) { return ({ draft: "Rascunho", published: "Publicada", archived: "Arquivada" })[status] || "Desconhecido"; }
    function statusBadge(status) { var cls = status === "published" ? "badge-success" : status === "draft" ? "badge-warning" : "badge-info"; return '<span class="badge ' + cls + '">' + esc(statusLabel(status)) + "</span>"; }
    function getRoute(id) { return state.items.find(function (item) { return item.__id === id; }) || null; }
    function selectedRouteIdsFor(establishmentId) { var item = state.establishments.find(function (entry) { return entry.__id === establishmentId; }); return H.unique(item && item.relationships && item.relationships.routeIds); }
    function associationCount(routeId) { return state.establishments.filter(function (item) { return selectedRouteIdsFor(item.__id).includes(routeId); }).length; }
    function render(container) {
        var target = container && container.nodeType === 1 ? container : section(); if (!target) return null;
        target.innerHTML = '<div class="page-header"><h1>🗺️ Rotas</h1><span class="badge badge-info">Admin V1.1</span></div>' +
          '<div class="card"><p class="admin-helper-text">Gerencie rotas temáticas em rascunho. A relação com empreendimentos é N:N e fica somente no catálogo interno.</p>' +
          '<div style="display:flex;flex-wrap:wrap;gap:.75rem;align-items:end"><div class="admin-field" style="margin:0"><label for="routesStatus">Status</label><select class="admin-input" id="routesStatus" onchange="AdminRoutesModule.onFilterChange()"><option value="all">Todos</option><option value="draft">Rascunho</option><option value="published">Publicada</option><option value="archived">Arquivada</option></select></div>' +
          '<div class="admin-field" style="margin:0;min-width:14rem"><label for="routesSearch">Buscar por nome ou slug</label><input class="admin-input" id="routesSearch" type="search" oninput="AdminRoutesModule.onFilterChange()"></div><div style="margin-left:auto;display:flex;gap:.5rem"><button class="btn-secondary" type="button" onclick="AdminRoutesModule.refresh()">↻ Atualizar</button><button class="btn-primary" type="button" onclick="AdminRoutesModule.openForm()">➕ Nova rota</button></div></div></div><div class="card"><div id="routes-list"></div></div>';
        document.getElementById("routesStatus").value = state.filterStatus; document.getElementById("routesSearch").value = state.query; renderList(); return target;
    }
    function renderList() {
        var target = document.getElementById("routes-list"); if (!target) return;
        if (state.loading) { return window.AdminUI.showLoading(target, "Carregando rotas..."); }
        if (state.error) { target.innerHTML = '<p style="text-align:center;padding:2rem;color:#b42318">' + esc(state.error) + '</p><p style="text-align:center"><button class="btn-secondary" type="button" onclick="AdminRoutesModule.refresh()">Tentar novamente</button></p>'; return; }
        var items = H.sortAndFilter(state.items, state.filterStatus, state.query);
        if (!items.length) { target.innerHTML = '<p style="text-align:center;padding:2rem;color:#888">' + esc(state.items.length ? "Nenhuma rota corresponde aos filtros." : "Nenhuma rota cadastrada. Use “Nova rota” para começar.") + "</p>"; return; }
        target.innerHTML = '<div style="overflow-x:auto"><table class="data-table"><thead><tr><th>Rota</th><th>Status</th><th>Empreendimentos</th><th>Ordem</th><th>Ações</th></tr></thead><tbody>' + items.map(function (item) {
          var cover = item.cover || {}, thumb = cover.url ? '<img src="' + esc(cover.url) + '" alt="' + esc(cover.alt || "Capa da rota") + '" style="width:56px;height:38px;object-fit:cover;border-radius:3px;vertical-align:middle;margin-right:.5rem" onerror="this.style.display=\'none\'">' : "";
          var actions = H.actionSet(item).map(function (action) { var label = ({edit:"Editar",preview:"Preview",publish:"Publicar",unpublish:"Despublicar",archive:"Arquivar"})[action]; var cls = action === "publish" ? "btn-primary" : "btn-secondary"; return '<button class="' + cls + ' btn-sm" type="button" onclick="AdminRoutesModule.' + action + '(\'' + js(item.__id) + '\')">' + label + "</button>"; }).join(" ");
          return '<tr><td>' + thumb + '<strong>' + esc(item.name || "Sem nome") + '</strong><br><small>' + esc(item.slug) + '</small></td><td>' + statusBadge(item.status) + '</td><td>' + associationCount(item.__id) + '</td><td>' + esc(String(item.displayOrder)) + '</td><td style="white-space:nowrap">' + actions + "</td></tr>";
        }).join("") + "</tbody></table></div>";
    }
    async function load() {
        if (!db()) { state.loading = false; state.error = "Firebase indisponível. Faça login no Admin e tente novamente."; renderList(); return false; }
        state.loading = true; state.error = ""; renderList();
        try { var results = await Promise.all([db().collection(ROUTES).get(), db().collection(ESTABLISHMENTS).get(), db().collection("media_library").get()]);
          state.items = results[0].docs.map(function (doc) { return Object.assign({ __id: doc.id }, doc.data()); });
          state.establishments = results[1].docs.map(function (doc) { return Object.assign({ __id: doc.id }, doc.data()); });
          state.media = results[2].docs.map(function (doc) { return Object.assign({ id: doc.id }, doc.data()); });
          state.loading = false; renderList(); return true;
        } catch (error) { state.loading = false; state.error = error && error.code === "permission-denied" ? "Permissão negada. Use uma conta administradora ativa no Emulator." : "Erro ao carregar Rotas. Tente novamente."; console.warn("[admin-routes] Falha de leitura.", error); renderList(); return false; }
    }
    function formValue(form, name) { return form.elements[name] ? form.elements[name].value : ""; }
    function fieldError(errors, name) { return errors && errors[name] ? '<small style="color:#b42318">' + esc(errors[name]) + "</small>" : ""; }
    function buildForm(item, errors) {
        item = item || {}; var isEdit = !!(item.__id || state.selectedId), locked = !!item.publishedAt, archived = item.status === "archived", cover = H.normalizeCover(item.cover), selected = item.__id ? state.establishments.filter(function (entry) { return selectedRouteIdsFor(entry.__id).includes(item.__id); }).map(function (entry) { return entry.__id; }) : (item && Object.keys(item).length ? state.selectedEstablishmentIds : []);
        state.selectedId = item.__id || (isEdit ? item.id : ""); state.selectedEstablishmentIds = selected;
        function input(label, name, value, extra) { return '<div class="admin-field"><label for="route_' + name + '">' + label + '</label><input class="admin-input" id="route_' + name + '" name="' + name + '" value="' + esc(value) + '" ' + (extra || "") + '>' + fieldError(errors, name) + "</div>"; }
        var disabled = archived ? " disabled" : "";
        return '<form id="routeForm" onsubmit="AdminRoutesModule.submitForm(event)"><div class="admin-modal-body"><input type="hidden" name="mode" value="' + (isEdit ? "edit" : "create") + '"><div class="admin-modal-grid">' +
          input("Nome", "name", item.name || "", "required" + disabled) + input("ID técnico", "id", item.__id || item.id || "", (isEdit ? "readonly" : "required") + disabled) +
          input("Slug", "slug", item.slug || "", (locked ? "readonly" : "required") + disabled) + input("Categoria", "category", item.category || "", "required" + disabled) +
          '<div class="admin-field full"><label for="route_description">Descrição</label><textarea class="admin-textarea" id="route_description" name="description" required' + disabled + '>' + esc(item.description || "") + '</textarea>' + fieldError(errors,"description") + "</div>" +
          input("Cor", "color", item.color || "#0b6e4f", "type=\"color\"" + disabled) + input("Ícone", "icon", item.icon || "🗺️", "required" + disabled) + input("Ordem de exibição", "displayOrder", item.displayOrder == null ? 10 : item.displayOrder, "type=\"number\" min=\"0\" max=\"100000\" required" + disabled) + input("Tags (separadas por vírgula)", "tags", (item.tags || []).join(", "), disabled) +
          '<div class="admin-field full"><label>Capa</label><input type="hidden" id="route_coverMediaId" name="coverMediaId" value="' + esc(cover.mediaId) + '"><input type="hidden" id="route_coverPath" name="coverPath" value="' + esc(cover.path) + '"><input class="admin-input" id="route_coverUrl" name="coverUrl" value="' + esc(cover.url) + '" readonly><button class="btn-secondary btn-sm" type="button" onclick="AdminRoutesModule.openMediaPicker()"' + disabled + '>Selecionar da biblioteca</button> <button class="btn-secondary btn-sm" type="button" onclick="AdminRoutesModule.clearCover()"' + disabled + '>Limpar referência</button>' + fieldError(errors,"cover") + '</div>' + input("Alt da capa", "coverAlt", cover.alt, "required" + disabled) +
          '<div class="admin-field full"><p class="admin-helper-text">O slug fica permanente após a primeira publicação. Status inicial: rascunho.</p><label for="route_establishmentSearch">Empreendimentos associados (<span id="routeSelectedCount">' + selected.length + '</span> selecionados)</label><input class="admin-input" id="route_establishmentSearch" type="search" placeholder="Buscar empreendimento" oninput="AdminRoutesModule.filterEstablishments()"><div id="routeEstablishmentList" style="max-height:15rem;overflow:auto;margin-top:.5rem"></div></div>' +
          '</div></div><div class="admin-modal-footer"><button class="btn-secondary" type="button" onclick="AdminRoutesModule.previewCurrentForm()">Preview</button><button class="btn-secondary" type="button" onclick="AdminRoutesModule.closeForm()">Cancelar</button>' + (archived ? "" : '<button class="btn-primary" type="submit" id="routeSaveButton">Salvar rota</button>') + "</div></form>";
    }
    function openForm(id, errors) { var item = id ? getRoute(id) : (state.pendingForm || null); state.pendingForm = null; modal(item ? (item.status === "archived" ? "Visualizar rota" : "Editar rota") : "Nova rota", buildForm(item, errors)); renderEstablishments(); if (!item) setTimeout(function () { var name = document.getElementById("route_name"); if (name) name.focus(); }, 0); }
    function renderEstablishments() { var target = document.getElementById("routeEstablishmentList"), search = H.clean(document.getElementById("route_establishmentSearch") && document.getElementById("route_establishmentSearch").value).toLowerCase(); if (!target) return; var rows = state.establishments.filter(function (item) { return !search || (H.clean(item.name) + " " + H.clean(item.category)).toLowerCase().includes(search); }); target.innerHTML = rows.length ? rows.map(function (item) { var checked = state.selectedEstablishmentIds.includes(item.__id); return '<label style="display:flex;gap:.5rem;padding:.35rem 0"><input type="checkbox" value="' + esc(item.__id) + '" ' + (checked ? "checked" : "") + ' onchange="AdminRoutesModule.toggleEstablishment(this)"><span><strong>' + esc(item.name || "Sem nome") + '</strong><br><small>' + esc(item.category || "Sem categoria") + (item.status ? " · " + esc(item.status) : "") + "</small></span></label>"; }).join("") : '<p class="admin-helper-text">Nenhum empreendimento encontrado.</p>'; }
    function readForm() { var form = document.getElementById("routeForm"), existing = state.selectedId ? getRoute(state.selectedId) : null; return H.serializeForm({ id: formValue(form,"id"), slug: formValue(form,"slug"), name: formValue(form,"name"), category: formValue(form,"category"), description: formValue(form,"description"), color: formValue(form,"color"), icon: formValue(form,"icon"), displayOrder: formValue(form,"displayOrder"), tags: formValue(form,"tags"), coverMediaId: formValue(form,"coverMediaId"), coverUrl: formValue(form,"coverUrl"), coverPath: formValue(form,"coverPath"), coverAlt: formValue(form,"coverAlt") }, existing); }
    async function submitForm(event) { event.preventDefault(); if (!activeAdmin() || state.saving) return; var route = readForm(), existing = state.selectedId ? getRoute(state.selectedId) : null, validation = H.validateRoute(route, { slugLocked: !!(existing && existing.publishedAt), originalSlug: existing && existing.slug }); if (!validation.valid) { openForm(state.selectedId, validation.errors); return; }
        var duplicateSlug = state.items.some(function (item) { return item.__id !== route.id && item.slug === route.slug; }); if (duplicateSlug) { openForm(state.selectedId, { slug: "Já existe uma rota com este slug." }); return; }
        state.saving = true; var button = document.getElementById("routeSaveButton"); if (button) { button.disabled = true; button.textContent = "Salvando..."; }
        try { await saveRouteAndAssociations(route, existing); closeModal(); await load(); toast(existing ? "Rota atualizada." : "Rota criada.", "success"); } catch (error) { console.warn("[admin-routes] Falha ao salvar.", error); toast(error && error.code === "permission-denied" ? "Permissão negada ao salvar rota." : "Erro ao salvar rota.", "error"); } finally { state.saving = false; }
    }
    async function saveRouteAndAssociations(route, existing) {
        var userId = uid(), selected = H.unique(state.selectedEstablishmentIds), previous = existing ? state.establishments.filter(function (item) { return selectedRouteIdsFor(item.__id).includes(existing.__id); }).map(function (item) { return item.__id; }) : [], diff = H.associationDiff(previous, selected), changes = diff.addedEstablishmentIds.concat(diff.removedEstablishmentIds), routeRef = db().collection(ROUTES).doc(route.id);
        await db().runTransaction(async function (transaction) {
            var reads = [transaction.get(routeRef)].concat(changes.map(function (id) { return transaction.get(db().collection(ESTABLISHMENTS).doc(id)); })); var snapshots = await Promise.all(reads);
            if (!existing && snapshots[0].exists) { var conflict = new Error("ID técnico já existe."); conflict.code = "already-exists"; throw conflict; }
            var payload = Object.assign({}, route, { updatedAt: ts(), updatedBy: userId });
            if (!existing) Object.assign(payload, { status: "draft", createdAt: ts(), createdBy: userId, publishedAt: null, publishedBy: "", archivedAt: null, archivedBy: "" });
            if (existing) transaction.set(routeRef, payload); else transaction.set(routeRef, payload);
            changes.forEach(function (id, index) { var snap = snapshots[index + 1]; if (!snap.exists) return; var data = snap.data() || {}, selectedNow = diff.addedEstablishmentIds.includes(id); transaction.update(snap.ref, { "relationships.routeIds": H.mergeRouteId(data.relationships && data.relationships.routeIds, route.id, selectedNow), updatedAt: ts(), updatedBy: userId }); });
        });
    }
    async function transition(id, target) { if (!activeAdmin() || state.saving) return; var item = getRoute(id); if (!item || !H.actionSet(item).includes(target === "published" ? "publish" : target === "draft" ? "unpublish" : "archive")) return; var messages = { published: "Publicar esta rota?", draft: "Despublicar esta rota?", archived: "Arquivar esta rota? Na V1.1 uma rota arquivada não pode ser restaurada." }; if (!window.confirm(messages[target])) return; state.saving = true; try { var fields = { status: target, updatedAt: ts(), updatedBy: uid() }; if (target === "published" && !item.publishedAt) { fields.publishedAt = ts(); fields.publishedBy = uid(); } if (target === "archived") { fields.archivedAt = ts(); fields.archivedBy = uid(); } await db().collection(ROUTES).doc(id).update(fields); await load(); toast(target === "published" ? "Rota publicada." : target === "draft" ? "Rota despublicada." : "Rota arquivada.", "success"); } catch (error) { console.warn("[admin-routes] Falha de transição.", error); toast("Erro ao alterar o status da rota.", "error"); } finally { state.saving = false; } }
    function preview(item) { item = item || readForm(); var cover = H.normalizeCover(item.cover); modal("Preview da rota", '<div class="admin-modal-body"><article style="border-left:6px solid ' + esc(item.color || "#0b6e4f") + ';padding:1rem"><img src="' + esc(cover.url) + '" alt="' + esc(cover.alt) + '" style="width:100%;max-height:220px;object-fit:cover" onerror="this.style.display=\'none\'"><p>' + esc(item.icon) + ' · ' + esc(item.category) + '</p><h3>' + esc(item.name) + '</h3><p>' + esc(item.description) + '</p><p><small>' + esc((item.tags || []).join(" · ")) + '</small></p></article></div><div class="admin-modal-footer"><button class="btn-secondary" type="button" onclick="AdminRoutesModule.closeForm()">Fechar</button></div>'); }
    var module = { id: SECTION_ID, label: "Rotas", icon: "🗺️", requiredRole: "admin", navGroup: "Conteúdo", order: 42, render: render, load: load, activate: function (context) { render(section(), context); return load(); }, refresh: load, onFilterChange: function () { state.filterStatus = document.getElementById("routesStatus").value; state.query = document.getElementById("routesSearch").value; renderList(); }, openForm: openForm, edit: openForm, submitForm: submitForm, closeForm: closeModal, filterEstablishments: renderEstablishments, toggleEstablishment: function (box) { state.selectedEstablishmentIds = H.unique((state.selectedEstablishmentIds || []).filter(function (id) { return id !== box.value; }).concat(box.checked ? [box.value] : [])); var count = document.getElementById("routeSelectedCount"); if (count) count.textContent = state.selectedEstablishmentIds.length; }, openMediaPicker: function () { state.pendingForm = readForm(); var list = state.media.map(function (item) { return '<button class="btn-secondary btn-sm" type="button" onclick="AdminRoutesModule.selectMedia(\'' + js(item.id) + '\')">' + esc(item.title || item.id) + "</button>"; }).join(" ") || "Nenhuma mídia disponível."; modal("Selecionar capa da biblioteca", '<div class="admin-modal-body"><p class="admin-helper-text">Selecione uma mídia existente. Nenhum upload será criado para Rotas.</p><div style="display:flex;flex-wrap:wrap;gap:.5rem">' + list + '</div></div><div class="admin-modal-footer"><button class="btn-secondary" type="button" onclick="AdminRoutesModule.openForm(\'\')">Voltar</button></div>'); }, selectMedia: function (id) { var item = state.media.find(function (media) { return media.id === id; }); if (!item || !state.pendingForm) return; state.pendingForm.cover = { mediaId: item.id, url: H.clean(item.url), path: H.clean(item.storagePath || item.path), alt: H.clean(item.alt || item.title || state.pendingForm.name) }; state.pendingForm.coverMediaId = state.pendingForm.cover.mediaId; state.pendingForm.coverUrl = state.pendingForm.cover.url; state.pendingForm.coverPath = state.pendingForm.cover.path; state.pendingForm.coverAlt = state.pendingForm.cover.alt; openForm(""); }, clearCover: function () { document.getElementById("route_coverMediaId").value=""; document.getElementById("route_coverUrl").value=""; document.getElementById("route_coverPath").value=""; }, preview: function (id) { preview(getRoute(id)); }, previewCurrentForm: function () { preview(); }, publish: function (id) { return transition(id,"published"); }, unpublish: function (id) { return transition(id,"draft"); }, archive: function (id) { return transition(id,"archived"); }, _state: state, _helpers: H };
    if (window.AdminRegistry && window.AdminRegistry.register) window.AdminRegistry.register(module); window.AdminRoutesModule = module;
})();
